### PR TITLE
RCPS-121 User Management System - Registering Student First Name not accept spacing

### PR DESCRIPTION
**Pull request by kylmrcdr123**
The user tries to enter their first name with spacing Ex: “Justine Dave”. But the system skips the Middle  Name field input and proceeds to Sex field input.

### CODE REVIEW

**Review by RoCS2024 — APPROVED** [review]

**Review by RoCS2024 — CHANGES_REQUESTED** [review]
most of the packages were rename. please get the recent changes by Kyle then do over

**Comment by kylmrcdr123** [comment]
> most of the packages were rename. please get the recent changes by Kyle then do over

i pulled the newly merged sir

**Review by RoCS2024 — CHANGES_REQUESTED** [review]
nothing has changed. the packages are still the same.

**Comment by RoCS2024** [comment]
same problem 
image

**Review by RoCS2024 — CHANGES_REQUESTED** [review]
same problem

**Pull request closed without merging**
